# fly.toml app configuration file generated for pitchify-server on 2023-04-25T12:24:20+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pitchify-server"
primary_region = "ams"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
